version: '3'

services:
  app:
    image: jasonxh/openhabcloud-app:latest
    build:
      context: ../..
      # Uncomment to customize timezone
      args:
        TZ: America/Los_Angeles
    volumes:
    - ./config.json.template:/opt/openhabcloud/config.json.template
    depends_on:
    - mongodb
    - redis
    restart: always
    environment:
    - DOMAIN_NAME
    - EXPRESS_KEY
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    - "traefik.port=3000"
    - "traefik.protocol=http"

  mongodb:
    image: mongo:4.2
    volumes:
    - mongo-data:/data/db
    restart: always

  redis:
    image: bitnami/redis:latest
    environment:
    - REDIS_PASSWORD=123_openHAB
    restart: always

  google-assistant:
    image: jasonxh/openhab-google-assistant:latest
    command: [ "--oh-host", "${DOMAIN_NAME}" ]
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=PathPrefixStrip:/google-assistant"
    - "traefik.port=3000"
    - "traefik.protocol=http"

  traefik:
    image: traefik:1.7
    ports:
    - "443:443"
    - "80:80"
    - "8080:8080"
    volumes:
    - ./traefik.toml:/etc/traefik/traefik.toml:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - traefik-data:/data
    command:
    - "--acme.email=${EMAIL}"
    restart: always

volumes:
  mongo-data:
  traefik-data:
